---
kafka_node_count: 3  # Number of Kafka nodes to be set up
kafka_install_dir: "/opt/kafka"
kafka_port: 9092
kafka_log_dirs: "/var/lib/kafka/logs"
kafka_config_dir: "{{ kafka_install_dir }}/config"
kafka_data_dir: "/var/lib/kafka/data"
